version: "3.9"
services:
  app:
    container_name: app-container
    #build: .
    image: marc0franc0/app-school-magement:1.0.1
    ports:
      - "9090:8080"
    restart: always
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/note_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET_KEY: 76397924423F4528482B4D6251655468576D5A7134743777217A25432A46294A
      JWT_TIME_EXPIRATION: 86400000
    networks:
      - app-db
  db:
    container_name: db-container
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: note_management
    ports:
      - "3306:3306"
    networks:
      - app-db
networks:
 app-db: